extends RefCounted
class_name UnilearnAchievementCatalog

const VERSION := 9

const ACHIEVEMENTS: Array[Dictionary] = [
	{"id":"a_fresh_start","number":1,"category":"ADDED BODIES","rarity":"normal","title":"A Fresh Start","description":"Add your 1st cosmic body to the simulator scene.","stages":[{"tier":1,"suffix":"I","description":"Add your 1st cosmic body to the simulator scene."}, {"tier":2,"suffix":"II","description":"Add 30 different cosmic bodies to the simulator scene."}, {"tier":3,"suffix":"III","description":"Add 70 different cosmic bodies to the simulator scene."}]},
	{"id":"life_beyond_earth","number":2,"category":"ADDED BODIES","rarity":"normal","title":"Life Beyond Earth","description":"Add 1 exoplanet with at least 90 habitability.","stages":[{"tier":1,"suffix":"I","description":"Add 1 exoplanet with at least 90 habitability."}, {"tier":2,"suffix":"II","description":"Add 5 different exoplanets with at least 90 habitability."}, {"tier":3,"suffix":"III","description":"Add 10 different exoplanets with at least 90 habitability."}]},
	{"id":"the_chosen_one","number":3,"category":"ADDED BODIES","rarity":"normal","title":"The Chosen One","description":"Add 1 exoplanet with at least 4 stats above 80.","stages":[{"tier":1,"suffix":"I","description":"Add 1 exoplanet with at least 4 stats above 80."}, {"tier":2,"suffix":"II","description":"Add 1 level 5 exoplanet with at least 4 stats above 80."}, {"tier":3,"suffix":"III","description":"Add 1 level 10 exoplanet with at least 4 stats above 80."}]},
	{"id":"give_me_that_ring","number":4,"category":"ADDED BODIES","rarity":"normal","title":"Give me that Ring!","description":"Add 1 ringed exoplanet to the simulator scene.","stages":[{"tier":1,"suffix":"I","description":"Add 1 ringed exoplanet to the simulator scene."}, {"tier":2,"suffix":"II","description":"Add 3 different ringed exoplanets to the simulator scene."}, {"tier":3,"suffix":"III","description":"Add 5 different ringed exoplanets to the simulator scene."}]},
	{"id":"gas_titan","number":5,"category":"ADDED BODIES","rarity":"normal","title":"Gas Titan","description":"Add 1 gas giant exoplanet with at least x3 Jupiter's diameter to the simulator scene.","stages":[{"tier":1,"suffix":"I","description":"Add 1 gas giant exoplanet with at least x3 Jupiter's diameter to the simulator scene."}, {"tier":2,"suffix":"II","description":"Add 3 different giant exoplanets with at least x3 Jupiter's diameter to the simulator scene."}, {"tier":3,"suffix":"III","description":"Add 5 different giant exoplanets with at least x3 Jupiter's diameter to the simulator scene."}]},
	{"id":"toxic_traits","number":6,"category":"ADDED BODIES","rarity":"normal","title":"Toxic Traits","description":"Add 1 exoplanet with less than 5 radiation safety.","stages":[{"tier":1,"suffix":"I","description":"Add 1 exoplanet with less than 5 radiation safety."}, {"tier":2,"suffix":"II","description":"Add 3 different exoplanets with less than 5 radiation safety."}, {"tier":3,"suffix":"III","description":"Add 5 different exoplanets with less than 5 radiation safety."}]},
	{"id":"star_of_the_show","number":7,"category":"ADDED BODIES","rarity":"normal","title":"Star of The Show","description":"Add 1 star from outside our solar system in the simulator scene.","stages":[{"tier":1,"suffix":"I","description":"Add 1 star from outside our solar system in the simulator scene."}, {"tier":2,"suffix":"II","description":"Add 5 different stars from outside our solar system in the simulator scene."}, {"tier":3,"suffix":"III","description":"Add 10 different stars from outside our solar system in the simulator scene."}]},
	{"id":"diamonds","number":8,"category":"ADDED BODIES","rarity":"rare","title":"Diamonds?","description":"Add 1 exoplanet with at least 95 geology.","stages":[{"tier":1,"suffix":"I","description":"Add 1 exoplanet with at least 95 geology."}, {"tier":2,"suffix":"II","description":"Add 1 exoplanet with at least 95 geology and level 5."}, {"tier":3,"suffix":"III","description":"Add 1 exoplanet with at least 95 geology and level 10."}]},
	{"id":"the_pull_of_the_universe","number":9,"category":"ADDED BODIES","rarity":"rare","title":"The Pull of The Universe","description":"Add 1 exoplanet with at least 95 gravity.","stages":[{"tier":1,"suffix":"I","description":"Add 1 exoplanet with at least 95 gravity."}, {"tier":2,"suffix":"II","description":"Add 1 exoplanet with at least 95 gravity and level 5."}, {"tier":3,"suffix":"III","description":"Add 1 exoplanet with at least 95 gravity and level 10."}]},
	{"id":"unknown_moon","number":10,"category":"ADDED BODIES","rarity":"rare","title":"Unknown Moon","description":"Add Saturn's moon, Mimas, in the simulator scene.","stages":[{"tier":1,"suffix":"I","description":"Add Saturn's moon, Mimas, in the simulator scene."}, {"tier":2,"suffix":"II","description":"Add Saturn's moon, Mimas, with level 5 in the simulator scene"}, {"tier":3,"suffix":"III","description":"Add Saturn's moon, Mimas, with level 10 in the simulator scene"}]},
	{"id":"big_bang","number":11,"category":"PLANET COLLISIONS","rarity":"normal","title":"Big Bang","description":"Collide your first 2 cosmic bodies.","stages":[{"tier":1,"suffix":"I","description":"Collide your first 2 cosmic bodies."}, {"tier":2,"suffix":"II","description":"Simulate 30 collisions between cosmic bodies."}, {"tier":3,"suffix":"III","description":"Simulate 70 collisions between cosmic bodies."}]},
	{"id":"not_quite_a_planet","number":12,"category":"PLANET COLLISIONS","rarity":"normal","title":"Not Quite a Planet","description":"Collide moons until they become the size of a planet.","stages":[{"tier":1,"suffix":"I","description":"Collide moons until they become the size of a planet."}, {"tier":2,"suffix":"II","description":"Create 10 planet-sized bodies from moon collisions."}, {"tier":3,"suffix":"III","description":"Create 30 planet-sized bodies from moon collisions."}]},
	{"id":"this_was_not_supposed_to_happen","number":13,"category":"PLANET COLLISIONS","rarity":"normal","title":"This Was Not Supposed to Happen","description":"Collide all moons of a planet into another planet.","stages":[{"tier":1,"suffix":"I","description":"Collide all moons of a planet into another planet."}, {"tier":2,"suffix":"II","description":"Collide all moons of a planet into another planet 5 times."}, {"tier":3,"suffix":"III","description":"Collide all moons of a planet into another planet 10 times."}]},
	{"id":"magneto_s_helmet_origins","number":14,"category":"PLANET COLLISIONS","rarity":"normal","title":"Magneto's Helmet Origins","description":"Collide 2 planets with at least 90 magnetic field.","stages":[{"tier":1,"suffix":"I","description":"Collide 2 planets with at least 90 magnetic field."}, {"tier":2,"suffix":"II","description":"Collide 10 pairs of planets with at least 90 magnetic field."}, {"tier":3,"suffix":"III","description":"Collide 30 pairs of planets with at least 90 magnetic field."}]},
	{"id":"breath_taking","number":15,"category":"PLANET COLLISIONS","rarity":"normal","title":"Breath-Taking!","description":"Collide 2 planets with less than 10 atmosphere.","stages":[{"tier":1,"suffix":"I","description":"Collide 2 planets with less than 10 atmosphere."}, {"tier":2,"suffix":"II","description":"Collide 10 pairs of planets with less than 10 atmosphere."}, {"tier":3,"suffix":"III","description":"Collide 30 pairs of planets with less than 10 atmosphere."}]},
	{"id":"so_close","number":16,"category":"PLANET COLLISIONS","rarity":"normal","title":"So Close...","description":"Collide planets until they become the size of a brown dwarf.","stages":[{"tier":1,"suffix":"I","description":"Collide planets until they become the size of a brown dwarf."}, {"tier":2,"suffix":"II","description":"Create 10 brown dwarfs from planet collisions."}, {"tier":3,"suffix":"III","description":"Create 30 brown dwarfs from planet collisions."}]},
	{"id":"no_hope_for_humanity","number":17,"category":"PLANET COLLISIONS","rarity":"normal","title":"No Hope For Humanity...","description":"Collide Earth a total of 21 times.","stages":[{"tier":1,"suffix":"I","description":"Collide Earth a total of 21 times."}, {"tier":2,"suffix":"II","description":"Collide Earth a total of 42 times."}, {"tier":3,"suffix":"III","description":"Collide Earth a total of 84 times (you really hate mankind)."}]},
	{"id":"extremes_belong_together","number":18,"category":"PLANET COLLISIONS","rarity":"rare","title":"Extremes Belong Together","description":"Collide 1 ice planet and 1 lava planet.","stages":[{"tier":1,"suffix":"I","description":"Collide 1 ice planet and 1 lava planet."}, {"tier":2,"suffix":"II","description":"Collide 1 level 5 ice planet and 1 level 5 lava planet."}, {"tier":3,"suffix":"III","description":"Collide 1 level 10 ice planet and 1 level 10 lava planet."}]},
	{"id":"how_did_we_get_here","number":19,"category":"PLANET COLLISIONS","rarity":"rare","title":"How Did We Get Here?","description":"Collide all 8 planets from our solar system into one single body.","stages":[{"tier":1,"suffix":"I","description":"Collide all 8 planets from our solar system into one single body."}, {"tier":2,"suffix":"II","description":"Collide all 8 planets with level 5 from our solar system into one single body."}, {"tier":3,"suffix":"III","description":"Collide all 8 planets with level 10 from our solar system into one single body."}]},
	{"id":"e_mc2","number":20,"category":"PLANET COLLISIONS","rarity":"rare","title":"E = mc²","description":"Collide 4 different planets, starting with the letters: E, M, C and C.","stages":[{"tier":1,"suffix":"I","description":"Collide 4 different planets, starting with the letters: E, M, C and C."}, {"tier":2,"suffix":"II","description":"Collide 4 different planets with level 5, starting with the letters: E, M, C and C."}, {"tier":3,"suffix":"III","description":"Collide 4 different planets with level 10, starting with the letters: E, M, C and C."}]},
	{"id":"needle_in_a_haystack","number":21,"category":"STAR COLLISIONS","rarity":"normal","title":"Needle in a Haystack","description":"Collide 1 moon into 1 star.","stages":[{"tier":1,"suffix":"I","description":"Collide 1 moon into 1 star."}, {"tier":2,"suffix":"II","description":"Collide 10 moons into stars."}, {"tier":3,"suffix":"III","description":"Collide 25 moons into stars."}]},
	{"id":"death_star","number":22,"category":"STAR COLLISIONS","rarity":"normal","title":"Death Star","description":"Collide 1 exoplanet with at least 80 habitability into a star.","stages":[{"tier":1,"suffix":"I","description":"Collide 1 exoplanet with at least 80 habitability into a star."}, {"tier":2,"suffix":"II","description":"Collide 5 different exoplanets with at least 80 habitability into stars."}, {"tier":3,"suffix":"III","description":"Collide 10 different exoplanets with at least 80 habitability into stars."}]},
	{"id":"planet_thief","number":23,"category":"STAR COLLISIONS","rarity":"normal","title":"Planet Thief","description":"Collide 1 planet orbiting a star into another star.","stages":[{"tier":1,"suffix":"I","description":"Collide 1 planet orbiting a star into another star."}, {"tier":2,"suffix":"II","description":"Steal 10 orbiting planets by colliding them into another star."}, {"tier":3,"suffix":"III","description":"Steal 30 orbiting planets by colliding them into another star."}]},
	{"id":"binary_breakup","number":24,"category":"STAR COLLISIONS","rarity":"normal","title":"Binary Breakup","description":"Collide 2 stars with similar mass and diameter.","stages":[{"tier":1,"suffix":"I","description":"Collide 2 stars with similar mass and diameter."}, {"tier":2,"suffix":"II","description":"Collide 5 pairs of stars with similar mass and diameter."}, {"tier":3,"suffix":"III","description":"Collide 15 pairs of stars with similar mass and diameter."}]},
	{"id":"triple_trouble","number":25,"category":"STAR COLLISIONS","rarity":"normal","title":"Triple Trouble","description":"Collide 3 stars within 10 seconds.","stages":[{"tier":1,"suffix":"I","description":"Collide 3 stars within 10 seconds."}, {"tier":2,"suffix":"II","description":"Collide 4 stars within 7 seconds."}, {"tier":3,"suffix":"III","description":"Collide 5 stars within 5 seconds."}]},
	{"id":"start_end","number":26,"category":"STAR COLLISIONS","rarity":"normal","title":"Start & End","description":"Collide 1 white dwarf and 1 brown dwarf.","stages":[{"tier":1,"suffix":"I","description":"Collide 1 white dwarf and 1 brown dwarf."}, {"tier":2,"suffix":"II","description":"Collide 5 white dwarf and brown dwarf pairs."}, {"tier":3,"suffix":"III","description":"Collide 15 white dwarf and brown dwarf pairs."}]},
	{"id":"life_s_not_fair","number":27,"category":"STAR COLLISIONS","rarity":"normal","title":"Life's Not Fair","description":"Collide 1 very small star with a very big star.","stages":[{"tier":1,"suffix":"I","description":"Collide 1 very small star with a very big star."}, {"tier":2,"suffix":"II","description":"Collide 5 very small stars into very big stars."}, {"tier":3,"suffix":"III","description":"Collide 10 very small stars into very big stars."}]},
	{"id":"a_girl_s_fight","number":28,"category":"STAR COLLISIONS","rarity":"rare","title":"A Girl's Fight","description":"Collide 2 brown dwarfs to form a real star.","stages":[{"tier":1,"suffix":"I","description":"Collide 2 brown dwarfs to form a real star."}, {"tier":2,"suffix":"II","description":"Collide 2 brown dwarfs with level 5 to form a real star."}, {"tier":3,"suffix":"III","description":"Collide 2 brown dwarfs with level 10 to form a real star."}]},
	{"id":"unlocking_supernova","number":29,"category":"STAR COLLISIONS","rarity":"rare","title":"Unlocking Supernova!","description":"Collide 2 red giant stars.","stages":[{"tier":1,"suffix":"I","description":"Collide 2 red giant stars."}, {"tier":2,"suffix":"II","description":"Collide 2 red giant stars with level 5."}, {"tier":3,"suffix":"III","description":"Collide 2 red giant stars with level 10."}]},
	{"id":"all_inclusive","number":30,"category":"STAR COLLISIONS","rarity":"rare","title":"All Inclusive!","description":"Collide 1 star of each known color into one body.","stages":[{"tier":1,"suffix":"I","description":"Collide 1 star of each known color into one body."}, {"tier":2,"suffix":"II","description":"Collide 1 level 5 star of each known color into one body."}, {"tier":3,"suffix":"III","description":"Collide 1 level 10 star of each known color into one body."}]},
	{"id":"black_magic","number":31,"category":"BLACK HOLES","rarity":"normal","title":"Black Magic!","description":"Unlock your 1st black hole.","stages":[{"tier":1,"suffix":"I","description":"Unlock your 1st black hole."}, {"tier":2,"suffix":"II","description":"Unlock 5 black holes."}, {"tier":3,"suffix":"III","description":"Unlock 10 black holes."}]},
	{"id":"the_dark_side_of_the_moon","number":32,"category":"BLACK HOLES","rarity":"normal","title":"The Dark Side of The Moon","description":"Make 1 black hole swallow 1 moon.","stages":[{"tier":1,"suffix":"I","description":"Make 1 black hole swallow 1 moon."}, {"tier":2,"suffix":"II","description":"Make 1 black hole swallow 10 moons."}, {"tier":3,"suffix":"III","description":"Make 1 black hole swallow 30 moons."}]},
	{"id":"the_formation_of_a_galaxy","number":33,"category":"BLACK HOLES","rarity":"normal","title":"The Formation of a Galaxy","description":"Make 1 star orbit 1 black hole.","stages":[{"tier":1,"suffix":"I","description":"Make 1 star orbit 1 black hole."}, {"tier":2,"suffix":"II","description":"Make 5 different stars orbit 1 black hole at once."}, {"tier":3,"suffix":"III","description":"Make 10 different stars orbit 1 black hole at once."}]},
	{"id":"forbidden_orbit","number":34,"category":"BLACK HOLES","rarity":"normal","title":"Forbidden Orbit","description":"Make 1 moon orbit 1 black hole.","stages":[{"tier":1,"suffix":"I","description":"Make 1 moon orbit 1 black hole."}, {"tier":2,"suffix":"II","description":"Make 5 moons orbit 1 black hole at once."}, {"tier":3,"suffix":"III","description":"Make 10 moons orbit 1 black hole at once."}]},
	{"id":"lights_out","number":35,"category":"BLACK HOLES","rarity":"normal","title":"Lights Out!","description":"Make 1 black hole swallow 1 blue star.","stages":[{"tier":1,"suffix":"I","description":"Make 1 black hole swallow 1 blue star."}, {"tier":2,"suffix":"II","description":"Make 1 black hole swallow 5 different blue stars."}, {"tier":3,"suffix":"III","description":"Make 1 black holes swallow 10 different blue stars."}]},
	{"id":"star_soup","number":36,"category":"BLACK HOLES","rarity":"normal","title":"Star Soup","description":"Make 1 black hole swallow 3 stars in less than 10 seconds.","stages":[{"tier":1,"suffix":"I","description":"Make 1 black hole swallow 3 stars in less than 10 seconds."}, {"tier":2,"suffix":"II","description":"Make 1 black hole swallow 3 stars in less than 7 seconds."}, {"tier":3,"suffix":"III","description":"Make 1 black hole swallow 3 stars in less than 4 seconds."}]},
	{"id":"gravity_bender","number":37,"category":"BLACK HOLES","rarity":"normal","title":"Gravity Bender","description":"Make 2 black holes collide, creating a supermassive black hole.","stages":[{"tier":1,"suffix":"I","description":"Make 2 black holes collide, creating a supermassive black hole."}, {"tier":2,"suffix":"II","description":"Create 5 supermassive black holes from black hole collisions."}, {"tier":3,"suffix":"III","description":"Create 10 supermassive black holes from black hole collisions."}]},
	{"id":"white_magic","number":38,"category":"BLACK HOLES","rarity":"rare","title":"White Magic!","description":"Unlock your 1st white hole, a theoretical cosmic body.","stages":[{"tier":1,"suffix":"I","description":"Unlock your 1st white hole, a theoretical cosmic body."}, {"tier":2,"suffix":"II","description":"Get the white hole to level 5."}, {"tier":3,"suffix":"III","description":"Get the white hole to level 10."}]},
	{"id":"cosmic_eraser","number":39,"category":"BLACK HOLES","rarity":"rare","title":"Cosmic Eraser","description":"Make 1 black hole swallow an entire system formed from at least 1 star and 5 planets.","stages":[{"tier":1,"suffix":"I","description":"Make 1 black hole swallow an entire system formed from at least 1 star and 5 planets."}, {"tier":2,"suffix":"II","description":"Make 1 black hole swallow an entire system formed from at least 1 level 5 star and 5 level 5 planets."}, {"tier":3,"suffix":"III","description":"Make 1 black hole swallow an entire system formed from at least 1 level 10 star and 5 level 10 planets."}]},
	{"id":"the_end_of_the_universe","number":40,"category":"BLACK HOLES","rarity":"rare","title":"The End of The Universe","description":"Make 1 black hole and 1 white hole collide.","stages":[{"tier":1,"suffix":"I","description":"Make 1 black hole and 1 white hole collide."}, {"tier":2,"suffix":"II","description":"Make 1 level 5 black hole and 1 level 5 white hole collide."}, {"tier":3,"suffix":"III","description":"Make 1 level 10 black hole and 1 level 10 white hole collide."}]},
	{"id":"we_ain_t_going_there","number":41,"category":"STAT MASTERY","rarity":"normal","title":"We Ain't Going There","description":"Create the worst possible system score, below 35.","stages":[{"tier":1,"suffix":"I","description":"Create the worst possible system score, below 35."}, {"tier":2,"suffix":"II","description":"Create a system with all 6 stats below 25. Why would you?"}, {"tier":3,"suffix":"III","description":"Create a system with all 6 stats below 10. Seriously, seek help."}]},
	{"id":"radiation_proof","number":42,"category":"STAT MASTERY","rarity":"normal","title":"Radiation Proof","description":"Reach at least 90 radiation safety while having at least 1 star.","stages":[{"tier":1,"suffix":"I","description":"Reach at least 90 radiation safety while having at least 1 star."}, {"tier":2,"suffix":"II","description":"Reach at least 90 radiation safety while having at least 1 star and 5 planets."}, {"tier":3,"suffix":"III","description":"Reach at least 90 radiation safety while having at least 1 star and 8 planets."}]},
	{"id":"rock_solid","number":43,"category":"STAT MASTERY","rarity":"normal","title":"Rock Solid","description":"Reach at least 90 geology and 90 magnetic field in the same system.","stages":[{"tier":1,"suffix":"I","description":"Reach at least 90 geology and 90 magnetic field in the same system."}, {"tier":2,"suffix":"II","description":"Reach at least 90 geology, 90 magnetic field, and 75 total system score."}, {"tier":3,"suffix":"III","description":"Reach at least 95 geology, 95 magnetic field, and 85 total system score."}]},
	{"id":"i_ve_won_but_at_what_cost","number":44,"category":"STAT MASTERY","rarity":"normal","title":"I've Won... But at What Cost?","description":"Reach at least 90 in one stat while having another stat below 25.","stages":[{"tier":1,"suffix":"I","description":"Reach at least 90 in one stat while having another stat below 25."}, {"tier":2,"suffix":"II","description":"Reach at least 95 in one stat while having another stat below 20."}, {"tier":3,"suffix":"III","description":"Reach 95 in one stat while having another stat below 15."}]},
	{"id":"moon_economy","number":45,"category":"STAT MASTERY","rarity":"normal","title":"Moon Economy","description":"Reach at least 75 system score with more moons than planets.","stages":[{"tier":1,"suffix":"I","description":"Reach at least 75 system score with more moons than planets."}, {"tier":2,"suffix":"II","description":"Reach at least 80 system score with more moons than planets."}, {"tier":3,"suffix":"III","description":"Reach at least 85 system score with more moons than planets."}]},
	{"id":"one_star_review","number":46,"category":"STAT MASTERY","rarity":"normal","title":"One-Star Review","description":"Build a system with exactly 1 star and at least 8 planets and reach at least an S grade.","stages":[{"tier":1,"suffix":"I","description":"Build a system with exactly 1 star and at least 8 planets and reach at least an S grade."}, {"tier":2,"suffix":"II","description":"Build a system with exactly 1 star, at least 8 planets, and at least 4 level 5 planets, then reach at least an S grade."}, {"tier":3,"suffix":"III","description":"Build a system with exactly 1 star, at least 8 planets, and at least 4 level 10 planets, then reach at least an S grade."}]},
	{"id":"overengineered","number":47,"category":"STAT MASTERY","rarity":"normal","title":"Overengineered","description":"Reach at least 85 system score with 12 or more active bodies.","stages":[{"tier":1,"suffix":"I","description":"Reach at least 85 system score with 12 or more active bodies."}, {"tier":2,"suffix":"II","description":"Reach at least 90 system score with 15 or more active bodies."}, {"tier":3,"suffix":"III","description":"Reach at least 95 system score with 16 active bodies."}]},
	{"id":"better_than_home","number":48,"category":"STAT MASTERY","rarity":"rare","title":"Better Than Home?","description":"Reach at least 80 score for each of the 6 stats.","stages":[{"tier":1,"suffix":"I","description":"Reach at least 80 score for each of the 6 stats."}, {"tier":2,"suffix":"II","description":"Reach at least 85 score for each of the 6 stats while using at least 3 level 5 planets."}, {"tier":3,"suffix":"III","description":"Reach at least 90 score for each of the 6 stats while using at least 3 level 10 planets."}]},
	{"id":"crowded_neighborhood","number":49,"category":"STAT MASTERY","rarity":"rare","title":"Crowded Neighborhood","description":"Build a system with 1 star, 10 planets, and 5 moons while keeping at least A grade.","stages":[{"tier":1,"suffix":"I","description":"Build a system with 1 star, 10 planets, and 5 moons while keeping at least A grade."}, {"tier":2,"suffix":"II","description":"Build a system with 1 star, 10 planets, 5 moons, and at least 5 level 5 planets while keeping at least A grade."}, {"tier":3,"suffix":"III","description":"Build a system with 1 star, 10 planets, 5 moons, and at least 5 level 10 planets while keeping at least A grade."}]},
	{"id":"omega_protocol","number":50,"category":"STAT MASTERY","rarity":"rare","title":"Omega Protocol","description":"Reach the Ω grade.","stages":[{"tier":1,"suffix":"I","description":"Reach the Ω grade."}, {"tier":2,"suffix":"II","description":"Reach the Ω grade with at least 5 level 5 planets in the system."}, {"tier":3,"suffix":"III","description":"Reach the Ω grade with at least 5 level 10 planets in the system."}]},
	{"id":"apollo_online","number":51,"category":"AI ASSISTANT","rarity":"normal","title":"Apollo Online","description":"Wake Apollo for the first time.","stages":[{"tier":1,"suffix":"I","description":"Wake Apollo for the first time."}, {"tier":2,"suffix":"II","description":"Wake Apollo 10 times."}, {"tier":3,"suffix":"III","description":"Wake Apollo 30 times."}]},
	{"id":"galaxy_remote","number":52,"category":"AI ASSISTANT","rarity":"normal","title":"Galaxy Remote","description":"Control the Galaxy Console through Apollo.","stages":[{"tier":1,"suffix":"I","description":"Control the Galaxy Console through Apollo."}, {"tier":2,"suffix":"II","description":"Use Apollo for 10 galaxy controls."}, {"tier":3,"suffix":"III","description":"Use Apollo for 25 galaxy controls."}]},
	{"id":"voice_of_the_cosmos","number":53,"category":"AI ASSISTANT","rarity":"normal","title":"Voice of The Cosmos","description":"Use different Apollo commands instead of repeating the same one.","stages":[{"tier":1,"suffix":"I","description":"Use 5 different Apollo commands."}, {"tier":2,"suffix":"II","description":"Use 15 different Apollo commands."}, {"tier":3,"suffix":"III","description":"Use every core Apollo command at least once."}]},
	{"id":"chain_reaction","number":54,"category":"AI ASSISTANT","rarity":"normal","title":"Chain Reaction","description":"Use linked Apollo commands in one single phrase.","stages":[{"tier":1,"suffix":"I","description":"Use 2 linked Apollo commands in one phrase."}, {"tier":2,"suffix":"II","description":"Use 3 linked Apollo commands in one phrase."}, {"tier":3,"suffix":"III","description":"Use 4 linked Apollo commands in one phrase."}]},
	{"id":"autopilot","number":55,"category":"AI ASSISTANT","rarity":"normal","title":"Autopilot","description":"Navigate somewhere in the app with Apollo.","stages":[{"tier":1,"suffix":"I","description":"Navigate somewhere in the app with Apollo."}, {"tier":2,"suffix":"II","description":"Navigate with Apollo 10 times."}, {"tier":3,"suffix":"III","description":"Navigate with Apollo 30 times."}]},
	{"id":"tiny_tweaks","number":56,"category":"AI ASSISTANT","rarity":"normal","title":"Tiny Tweaks","description":"Change an app setting with Apollo.","stages":[{"tier":1,"suffix":"I","description":"Change an app setting with Apollo."}, {"tier":2,"suffix":"II","description":"Change settings with Apollo 10 times."}, {"tier":3,"suffix":"III","description":"Change settings with Apollo 25 times."}]},
	{"id":"words_to_worlds","number":57,"category":"AI ASSISTANT","rarity":"normal","title":"Words to Worlds","description":"Create your first cosmic body through Apollo.","stages":[{"tier":1,"suffix":"I","description":"Create your first cosmic body through Apollo."}, {"tier":2,"suffix":"II","description":"Create 5 cosmic bodies through Apollo."}, {"tier":3,"suffix":"III","description":"Create 15 cosmic bodies through Apollo."}]},
	{"id":"no_wasted_motion","number":58,"category":"AI ASSISTANT","rarity":"rare","title":"No Wasted Motion","description":"Ask Apollo for something that is already done.","stages":[{"tier":1,"suffix":"I","description":"Ask Apollo for something that is already done."}, {"tier":2,"suffix":"II","description":"Get 5 already-done Apollo responses."}, {"tier":3,"suffix":"III","description":"Get 15 already-done Apollo responses."}]},
	{"id":"mission_control","number":59,"category":"AI ASSISTANT","rarity":"rare","title":"Mission Control","description":"Use 3 different types of Apollo actions.","stages":[{"tier":1,"suffix":"I","description":"Use 3 different types of Apollo actions."}, {"tier":2,"suffix":"II","description":"Use 5 different types of Apollo actions."}, {"tier":3,"suffix":"III","description":"Use 7 different types of Apollo actions."}]},
	{"id":"cosmic_comedian","number":60,"category":"AI ASSISTANT","rarity":"rare","title":"Cosmic Comedian","description":"Ask Apollo to tell jokes.","stages":[{"tier":1,"suffix":"I","description":"Ask Apollo to tell 1 joke."}, {"tier":2,"suffix":"II","description":"Ask Apollo to tell 5 jokes."}, {"tier":3,"suffix":"III","description":"Ask Apollo to tell 15 jokes."}]},
	{"id":"moon_master","number":61,"category":"UNSTABLE SYSTEMS","rarity":"normal","title":"Moon Master","description":"Create a system containing at least 5 moons orbiting a planet.","stages":[{"tier":1,"suffix":"I","description":"Create a system containing at least 5 moons orbiting a planet."}, {"tier":2,"suffix":"II","description":"Create a system containing at least 10 moons orbiting a planet."}, {"tier":3,"suffix":"III","description":"Create a system containing at least 15 moons orbiting a planet."}]},
	{"id":"frozen_wasteland","number":62,"category":"UNSTABLE SYSTEMS","rarity":"normal","title":"Frozen Wasteland","description":"Create a system containing at least 8 planets, without a star.","stages":[{"tier":1,"suffix":"I","description":"Create a system containing at least 8 planets, without a star."}, {"tier":2,"suffix":"II","description":"Create a system containing at least 12 planets, without a star."}, {"tier":3,"suffix":"III","description":"Create a system containing at least 16 planets, without a star."}]},
	{"id":"ra_s_empire","number":63,"category":"UNSTABLE SYSTEMS","rarity":"normal","title":"Ra's Empire","description":"Create a system with only stars, at least 4.","stages":[{"tier":1,"suffix":"I","description":"Create a system with only stars, at least 4."}, {"tier":2,"suffix":"II","description":"Create a system with only stars, at least 7."}, {"tier":3,"suffix":"III","description":"Create a system with only stars, at least 10."}]},
	{"id":"on_the_edge_of_extinction","number":64,"category":"UNSTABLE SYSTEMS","rarity":"normal","title":"On The Edge of Extinction","description":"Create a system with at least 8 planets and one red supergiant star.","stages":[{"tier":1,"suffix":"I","description":"Create a system with at least 8 planets and one red supergiant star."}, {"tier":2,"suffix":"II","description":"Create a system with at least 12 planets and one red supergiant star."}, {"tier":3,"suffix":"III","description":"Create a system with at least 15 planets and one red supergiant star."}]},
	{"id":"center_of_the_universe","number":65,"category":"UNSTABLE SYSTEMS","rarity":"normal","title":"Center of The Universe","description":"Create a system with 5 planets orbiting Earth.","stages":[{"tier":1,"suffix":"I","description":"Create a system with 5 planets orbiting Earth."}, {"tier":2,"suffix":"II","description":"Create a system with 8 planets orbiting Earth."}, {"tier":3,"suffix":"III","description":"Create a system with 10 planets orbiting Earth."}]},
	{"id":"dual_what","number":66,"category":"UNSTABLE SYSTEMS","rarity":"normal","title":"Dual What?","description":"Create a system with at least 8 planets, with 2 orbiting planets instead of a star.","stages":[{"tier":1,"suffix":"I","description":"Create a system with at least 8 planets, with 2 orbiting planets instead of a star."}, {"tier":2,"suffix":"II","description":"Create a system with at least 12 planets, with 2 orbiting planets instead of a star."}, {"tier":3,"suffix":"III","description":"Create a system with at least 15 planets, with 2 orbiting planets instead of a star."}]},
	{"id":"whoops_wrong_button","number":67,"category":"UNSTABLE SYSTEMS","rarity":"normal","title":"Whoops... Wrong Button","description":"Disable stable orbit mode, causing an 5 planets stable system to throw all planets into deep space.","stages":[{"tier":1,"suffix":"I","description":"Disable stable orbit mode, causing an 5 planets stable system to throw all planets into deep space."}, {"tier":2,"suffix":"II","description":"Disable stable orbit mode, causing a 8 planets stable system to throw all planets into deep space."}, {"tier":3,"suffix":"III","description":"Disable stable orbit mode, causing a 10 planets stable system to throw all planets into deep space."}]},
	{"id":"rogue_one","number":68,"category":"UNSTABLE SYSTEMS","rarity":"rare","title":"Rogue One","description":"Throw a planet 100.000 km away from the origin of the simulator scene.","stages":[{"tier":1,"suffix":"I","description":"Throw a planet 100.000 km away from the origin of the simulator scene."}, {"tier":2,"suffix":"II","description":"Throw a level 5 planet 100.000 km away from the origin of the simulator scene."}, {"tier":3,"suffix":"III","description":"Throw a level 10 planet 100.000 km away from the origin of the simulator scene."}]},
	{"id":"this_feels_more_like_reality","number":69,"category":"UNSTABLE SYSTEMS","rarity":"rare","title":"This Feels More Like Reality","description":"Disable the center anchor and throw the star into deep space, causing an infinitely moving system.","stages":[{"tier":1,"suffix":"I","description":"Disable the center anchor and throw the star into deep space, causing an infinitely moving system."}, {"tier":2,"suffix":"II","description":"Disable the center anchor and throw a system with at least 5 level 5 planets into deep space."}, {"tier":3,"suffix":"III","description":"Disable the center anchor and throw a system with at least 8 level 10 planets into deep space."}]},
	{"id":"game_s_broken_now","number":70,"category":"UNSTABLE SYSTEMS","rarity":"rare","title":"Game's Broken Now...","description":"Create a system with either a planet orbiting a moon, or a star orbiting a planet.","stages":[{"tier":1,"suffix":"I","description":"Create a system with either a planet orbiting a moon, or a star orbiting a planet."}, {"tier":2,"suffix":"II","description":"Create a system with a level 5 planet orbiting a moon, or a star orbiting a level 5 planet."}, {"tier":3,"suffix":"III","description":"Create a system with a level 10 planet orbiting a moon, or a star orbiting a level 10 planet."}]},
	{"id":"planet_collector","number":71,"category":"CARDS","rarity":"normal","title":"Planet Collector","description":"Create your 1st generated card.","stages":[{"tier":1,"suffix":"I","description":"Create your 1st generated card."}, {"tier":2,"suffix":"II","description":"Create 30 generated cards."}, {"tier":3,"suffix":"III","description":"Create 70 generated cards."}]},
	{"id":"lvl_up","number":72,"category":"CARDS","rarity":"normal","title":"Lvl Up!","description":"Upgrade any card to level 2.","stages":[{"tier":1,"suffix":"I","description":"Upgrade any card to level 2."}, {"tier":2,"suffix":"II","description":"Upgrade any card to level 5."}, {"tier":3,"suffix":"III","description":"Upgrade any card to level 10."}]},
	{"id":"moon_factory","number":73,"category":"CARDS","rarity":"normal","title":"Moon Factory","description":"Discover 10 moon cards.","stages":[{"tier":1,"suffix":"I","description":"Discover 10 moon cards."}, {"tier":2,"suffix":"II","description":"Discover 25 moon cards."}, {"tier":3,"suffix":"III","description":"Discover 50 moon cards."}]},
	{"id":"ice_age","number":74,"category":"CARDS","rarity":"normal","title":"Ice Age","description":"Discover 5 new ice world cards.","stages":[{"tier":1,"suffix":"I","description":"Discover 5 new ice world cards."}, {"tier":2,"suffix":"II","description":"Discover 15 new ice world cards."}, {"tier":3,"suffix":"III","description":"Discover 30 new ice world cards."}]},
	{"id":"gas_dealer","number":75,"category":"CARDS","rarity":"normal","title":"Gas Dealer","description":"Discover 5 new gas giant cards.","stages":[{"tier":1,"suffix":"I","description":"Discover 5 new gas giant cards."}, {"tier":2,"suffix":"II","description":"Discover 15 new gas giant cards."}, {"tier":3,"suffix":"III","description":"Discover 30 new gas giant cards."}]},
	{"id":"terra_hunter","number":76,"category":"CARDS","rarity":"normal","title":"Terra Hunter","description":"Discover 5 Earth-like or habitable planet cards.","stages":[{"tier":1,"suffix":"I","description":"Discover 5 Earth-like or habitable planet cards."}, {"tier":2,"suffix":"II","description":"Discover 15 Earth-like or habitable planet cards."}, {"tier":3,"suffix":"III","description":"Discover 30 Earth-like or habitable planet cards."}]},
	{"id":"it_s_not_real","number":77,"category":"CARDS","rarity":"normal","title":"It's Not Real!","description":"Create your 1st fictional cosmic body card.","stages":[{"tier":1,"suffix":"I","description":"Create your 1st fictional cosmic body card."}, {"tier":2,"suffix":"II","description":"Create 10 fictional cosmic body cards."}, {"tier":3,"suffix":"III","description":"Create 25 fictional cosmic body cards."}]},
	{"id":"failed_star_club","number":78,"category":"CARDS","rarity":"rare","title":"Failed Star Club","description":"Discover 3 brown dwarf cards.","stages":[{"tier":1,"suffix":"I","description":"Discover 3 brown dwarf cards."}, {"tier":2,"suffix":"II","description":"Discover 10 brown dwarf cards."}, {"tier":3,"suffix":"III","description":"Discover 25 brown dwarf cards."}]},
	{"id":"strange_new_worlds","number":79,"category":"CARDS","rarity":"rare","title":"Strange New Worlds","description":"Discover at least 1 card from each planet preset.","stages":[{"tier":1,"suffix":"I","description":"Discover at least 1 card from each planet preset."}, {"tier":2,"suffix":"II","description":"Discover at least 3 cards from each planet preset."}, {"tier":3,"suffix":"III","description":"Discover at least 5 cards from each planet preset."}]},
	{"id":"the_archivist","number":80,"category":"CARDS","rarity":"rare","title":"The Archivist","description":"Own 30 generated cards total.","stages":[{"tier":1,"suffix":"I","description":"Own 30 generated cards total."}, {"tier":2,"suffix":"II","description":"Own 70 generated cards total."}, {"tier":3,"suffix":"III","description":"Own 100 generated cards total."}]},
]

static func all() -> Array[Dictionary]:
	return ACHIEVEMENTS.duplicate(true)

static func get_by_id(id: String) -> Dictionary:
	var clean_id := normalize_id(id)
	for achievement in ACHIEVEMENTS:
		if str(achievement.get("id", "")) == clean_id:
			return achievement.duplicate(true)
	return {}

static func get_by_number(number_value: int) -> Dictionary:
	for achievement in ACHIEVEMENTS:
		if int(achievement.get("number", 0)) == int(number_value):
			return achievement.duplicate(true)
	return {}

static func normalize_id(value: String) -> String:
	var text := str(value).strip_edges().to_lower()
	text = text.replace("²", "2")
	var regex := RegEx.new()
	regex.compile("[^a-z0-9]+")
	text = regex.sub(text, "_", true)
	while text.begins_with("_"):
		text = text.substr(1)
	while text.ends_with("_"):
		text = text.substr(0, text.length() - 1)
	return text

static func stage_suffix_for_tier(_tier: int) -> String:
	return ""

static func stage_description(achievement: Dictionary, tier: int) -> String:
	var stages: Array = achievement.get("stages", [])
	var idx := clampi(int(tier) - 1, 0, max(stages.size() - 1, 0))
	if stages.size() > idx and stages[idx] is Dictionary:
		return str(stages[idx].get("description", achievement.get("description", "")))
	return str(achievement.get("description", ""))

static func make_locked_payload(achievement: Dictionary) -> Dictionary:
	return {
		"id": str(achievement.get("id", "")),
		"number": int(achievement.get("number", 0)),
		"category": str(achievement.get("category", "")),
		"title": "???",
		"description": "Hidden achievement",
		"unlocked": false,
		"hidden": true,
		"unlockedAtMs": 0,
	}

static func make_unlocked_payload(achievement: Dictionary, unlocked_at_ms: int = 0, tier: int = 1) -> Dictionary:
	var payload := achievement.duplicate(true)
	payload["title"] = str(achievement.get("title", "Achievement"))
	payload["base_title"] = str(achievement.get("title", "Achievement"))
	payload["description"] = stage_description(achievement, tier)
	payload["unlocked"] = true
	payload["tier"] = tier
	payload["unlockedAtMs"] = unlocked_at_ms
	return payload
